# Generated by Django 3.2.9 on 2021-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='balance',
            field=models.PositiveBigIntegerField(),
        ),
    ]
